<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>try</title>
</head>
<body>

<script type="text/javascript">
/*
    Error 通过Error的构造器可以创建一个错误对象
    EvalError 本对象代表了一个关于 eval 函数的错误
    InternalError InternalError 对象表示出现在JavaScript引擎内部的错误(不标准)
    RangeError 超过最小或者最大范围
    ReferenceError 一个不存在的变量被引用
    SyntaxError 语法错误
    TypeError　　表示值的类型非预期类型时发生的错误　
    URIError　　URL解析错误
*/
/*	try {
		try {
			throw new Error("自定义错误");
		} catch(e){
			console.log("内部捕获错误", e.message);
		} finally {
			console.log("内部的finally");
		}
	} catch(e){
		console.log("外部捕获错误", e.message);
	}
*/


    //错误是可以向外传递的，如果内层没有捕获错误，那么会传递给外部去捕获处理
   	try {
		try {
			throw new Error("自定义错误");
		} finally {
			console.log("内部的finally");
		}
	} catch(e){
		console.log("外部捕获错误", e.message);
	}


	console.log("运行完毕");

</script>

</body>
</html>
